## you dont need a production setting because heroku creates one for you.
default: &default
    adapter: postgresql
    database: blocipedia
    host: localhost
    pool: 5
    timeout: 5000

development:
  <<: *default
  database: blocipedia

test:
  <<: *default
  database: blocipedia_test
