# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a340e4b54b37aea92e14fd9903f5d1cc1e539989c2f9b2a4d7c0170cf502f18c256eda8c7700e3428d6b304b418ebb935eb8f5fda56d23d5ace255cd8ae6174e

test:
  secret_key_base: ec210dba403c1070515dd1ee796227aae1e2594127d306d90bac97afd1706c192b78cdbbded4992bfa53a2af954f67515ba23ba1aa53d4e416555481c0005f9f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
